// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusic() {
  return window['go']['main']['App']['GetMusic']();
}

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}
