// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetMusic():Promise<string>;

export function GetPeople():Promise<Array<main.Song>>;
